require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  
AllCops:
  NewCops: enable
  Exclude:
    - node_modules
    - public/**/*
    - vendor/**/*
    - bin/**/*
    - db/schema.rb
    
Rails:
  Enabled: true
RSpec:
  Enabled: true