default:
  models:
    Clinic: read
    Membership:
      - read
      - search

editor:
  models:

admin:
  includes:
    - physician
  manageable_roles:
    - admin
    - physician
  models:
    Clinic: manage
    Membership: manage
